"""fixing pnl

Revision ID: 2b4b25d854b9
Revises: cb2f38ebe22c
Create Date: 2025-07-09 18:08:58.319871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b4b25d854b9'
down_revision: Union[str, None] = 'cb2f38ebe22c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('realized_pnl', sa.Column('proceeds', sa.Numeric(), nullable=True))
    op.drop_column('realized_pnl', 'sale_price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('realized_pnl', sa.Column('sale_price', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.drop_column('realized_pnl', 'proceeds')
    # ### end Alembic commands ###
