"""adding prices table

Revision ID: 2d140f05f8ff
Revises: ef7eb888cf43
Create Date: 2025-05-26 10:06:30.951269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d140f05f8ff'
down_revision: Union[str, None] = 'ef7eb888cf43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prices',
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('price_date', sa.Date(), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.PrimaryKeyConstraint('symbol', 'price_date', name='pk_prices_symbol_date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prices')
    # ### end Alembic commands ###
