"""adding portfolio metrics 2

Revision ID: 4a4a0d053a5e
Revises: c835d543a66a
Create Date: 2025-06-06 17:51:00.935473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a4a0d053a5e'
down_revision: Union[str, None] = 'c835d543a66a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio_metrics_snapshot',
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('portfolio_value', sa.Numeric(), nullable=True),
    sa.Column('benchmark_value', sa.Numeric(), nullable=True),
    sa.Column('portfolio_daily_return', sa.Numeric(), nullable=True),
    sa.Column('benchmark_daily_return', sa.Numeric(), nullable=True),
    sa.Column('cash_balance', sa.Numeric(), nullable=True),
    sa.Column('twr_to_date', sa.Numeric(), nullable=True),
    sa.Column('rolling_return_7d', sa.Numeric(), nullable=True),
    sa.Column('rolling_return_30d', sa.Numeric(), nullable=True),
    sa.Column('sharpe_to_date', sa.Numeric(), nullable=True),
    sa.Column('drawdown_to_date', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.account_id'], ),
    sa.PrimaryKeyConstraint('snapshot_date', 'account_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('portfolio_metrics_snapshot')
    # ### end Alembic commands ###
