"""tracking actions

Revision ID: 4d0b893ea6d2
Revises: 29fb9164a95a
Create Date: 2025-05-24 21:10:13.194501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d0b893ea6d2'
down_revision: Union[str, None] = '29fb9164a95a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('position_snapshots', sa.Column('action', sa.String(), nullable=True))
    op.add_column('positions', sa.Column('action', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('positions', 'action')
    op.drop_column('position_snapshots', 'action')
    # ### end Alembic commands ###
