"""creating user level metrics

Revision ID: ab5aa82e0b6d
Revises: 2b4b25d854b9
Create Date: 2025-07-30 21:50:53.055078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab5aa82e0b6d'
down_revision: Union[str, None] = '2b4b25d854b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_portfolio_metrics_snapshot',
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('portfolio_value', sa.Numeric(), nullable=True),
    sa.Column('benchmark_value', sa.Numeric(), nullable=True),
    sa.Column('portfolio_daily_return', sa.Numeric(), nullable=True),
    sa.Column('benchmark_daily_return', sa.Numeric(), nullable=True),
    sa.Column('cash_balance', sa.Numeric(), nullable=True),
    sa.Column('twr_to_date', sa.Numeric(), nullable=True),
    sa.Column('rolling_return_7d', sa.Numeric(), nullable=True),
    sa.Column('rolling_return_30d', sa.Numeric(), nullable=True),
    sa.Column('sharpe_to_date', sa.Numeric(), nullable=True),
    sa.Column('drawdown_to_date', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('snapshot_date', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_portfolio_metrics_snapshot')
    # ### end Alembic commands ###
