"""create index on positions

Revision ID: b08204ed4703
Revises: 2d140f05f8ff
Create Date: 2025-05-30 18:29:19.337225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b08204ed4703'
down_revision: Union[str, None] = '2d140f05f8ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_account_symbol', 'positions', ['account_id', 'symbol'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_account_symbol', 'positions', type_='unique')
    # ### end Alembic commands ###
