"""realized pnl_2

Revision ID: cb2f38ebe22c
Revises: 305b34aea60f
Create Date: 2025-07-09 17:27:35.260278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb2f38ebe22c'
down_revision: Union[str, None] = '305b34aea60f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('realized_pnl',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('base_symbol', sa.String(), nullable=False),
    sa.Column('option_symbol', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('realized_pnl', sa.Numeric(), nullable=False),
    sa.Column('quantity_closed', sa.Numeric(), nullable=False),
    sa.Column('cost_basis', sa.Numeric(), nullable=True),
    sa.Column('sale_price', sa.Numeric(), nullable=True),
    sa.Column('action', sa.Enum('BUY', 'SELL', 'BUY_TO_OPEN', 'SELL_TO_OPEN', 'BUY_TO_CLOSE', 'SELL_TO_CLOSE', 'SELL_SHORT', 'DIVIDEND', 'JOURNAL', 'QUALIFIED_DIVIDEND', 'CASH_DIVIDEND', 'CREDIT_INTEREST', 'MARGIN_INTEREST', 'MONEYLINK_TRANSFER', 'JOURNALED_SHARES', 'BANK_INTEREST', name='transactiontype', native_enum=False), nullable=False),
    sa.Column('instrument_type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.account_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'option_symbol', 'date', name='uix_realized_pnl_contract')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('realized_pnl')
    # ### end Alembic commands ###
