"""tracking actions 1

Revision ID: ef7eb888cf43
Revises: 4d0b893ea6d2
Create Date: 2025-05-24 21:20:34.514068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef7eb888cf43'
down_revision: Union[str, None] = '4d0b893ea6d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('position_snapshots', 'action',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('positions', 'action',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('positions', 'action',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('position_snapshots', 'action',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
