"""adding metrics snapshot

Revision ID: f38dd6e6c33a
Revises: b08204ed4703
Create Date: 2025-06-01 19:43:05.304848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f38dd6e6c33a'
down_revision: Union[str, None] = 'b08204ed4703'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'action',
               existing_type=sa.VARCHAR(length=13),
               type_=sa.Enum('BUY', 'SELL', 'BUY_TO_OPEN', 'SELL_TO_OPEN', 'BUY_TO_CLOSE', 'SELL_TO_CLOSE', 'SELL_SHORT', 'DIVIDEND', 'JOURNAL', 'QUALIFIED_DIVIDEND', 'CASH_DIVIDEND', 'CREDIT_INTEREST', 'MARGIN_INTEREST', 'MONEYLINK_TRANSFER', 'JOURNALED_SHARES', name='transactiontype', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'action',
               existing_type=sa.Enum('BUY', 'SELL', 'BUY_TO_OPEN', 'SELL_TO_OPEN', 'BUY_TO_CLOSE', 'SELL_TO_CLOSE', 'SELL_SHORT', 'DIVIDEND', 'JOURNAL', 'QUALIFIED_DIVIDEND', 'CASH_DIVIDEND', 'CREDIT_INTEREST', 'MARGIN_INTEREST', 'MONEYLINK_TRANSFER', 'JOURNALED_SHARES', name='transactiontype', native_enum=False),
               type_=sa.VARCHAR(length=13),
               existing_nullable=False)
    # ### end Alembic commands ###
